//! Seccomp BPF filter using seccompiler.
//!
//! Default profile is deny-by-default: only explicitly allowed syscalls pass.
//! The BPF program is compiled once and cached for reuse across containers.

use crate::error::{Error, Result};
use crate::protocol::SeccompMode;
use seccompiler::{BpfProgram, SeccompAction, SeccompFilter, SeccompRule, TargetArch};
use std::collections::BTreeMap;
use std::sync::LazyLock;

/// Cached default seccomp BPF program.
static DEFAULT_FILTER: LazyLock<BpfProgram> = LazyLock::new(|| {
    build_default_filter().expect("failed to build default seccomp filter")
});

/// Apply the seccomp filter based on the configured mode.
/// This must be called in the child, after all other setup but before exec.
pub fn apply_seccomp(mode: &SeccompMode) -> Result<()> {
    match mode {
        SeccompMode::Default => {
            let filter = DEFAULT_FILTER.clone();
            seccompiler::apply_filter(&filter)
                .map_err(|e| Error::Seccomp(format!("failed to apply filter: {e}")))?;
            Ok(())
        }
        SeccompMode::Disabled => Ok(()),
    }
}

/// Build the default deny-by-default seccomp filter.
/// Allows a curated set of ~260 common syscalls needed for typical workloads.
fn build_default_filter() -> std::result::Result<BpfProgram, seccompiler::Error> {
    let mut rules: BTreeMap<i64, Vec<SeccompRule>> = BTreeMap::new();

    // Allow all these syscalls unconditionally
    for &syscall in ALLOWED_SYSCALLS {
        rules.insert(syscall, vec![SeccompRule::new(vec![])?]);
    }

    let filter = SeccompFilter::new(
        rules,
        // Default action: deny with EPERM (deny-by-default)
        SeccompAction::Errno(libc::EPERM as u32),
        // Action for allowed syscalls
        SeccompAction::Allow,
        TargetArch::x86_64,
    )?;

    let bpf: BpfProgram = filter.try_into().map_err(seccompiler::Error::from)?;
    Ok(bpf)
}

/// Syscalls allowed in the default profile.
/// This list covers typical container workloads (shell, file I/O, networking,
/// process management) while blocking dangerous syscalls like kexec_load,
/// mount (post-setup), ptrace, etc.
const ALLOWED_SYSCALLS: &[i64] = &[
    libc::SYS_read,
    libc::SYS_write,
    libc::SYS_open,
    libc::SYS_close,
    libc::SYS_stat,
    libc::SYS_fstat,
    libc::SYS_lstat,
    libc::SYS_poll,
    libc::SYS_lseek,
    libc::SYS_mmap,
    libc::SYS_mprotect,
    libc::SYS_munmap,
    libc::SYS_brk,
    libc::SYS_rt_sigaction,
    libc::SYS_rt_sigprocmask,
    libc::SYS_rt_sigreturn,
    libc::SYS_ioctl,
    libc::SYS_pread64,
    libc::SYS_pwrite64,
    libc::SYS_readv,
    libc::SYS_writev,
    libc::SYS_access,
    libc::SYS_pipe,
    libc::SYS_select,
    libc::SYS_sched_yield,
    libc::SYS_mremap,
    libc::SYS_msync,
    libc::SYS_mincore,
    libc::SYS_madvise,
    libc::SYS_shmget,
    libc::SYS_shmat,
    libc::SYS_shmctl,
    libc::SYS_dup,
    libc::SYS_dup2,
    libc::SYS_pause,
    libc::SYS_nanosleep,
    libc::SYS_getitimer,
    libc::SYS_alarm,
    libc::SYS_setitimer,
    libc::SYS_getpid,
    libc::SYS_sendfile,
    libc::SYS_socket,
    libc::SYS_connect,
    libc::SYS_accept,
    libc::SYS_sendto,
    libc::SYS_recvfrom,
    libc::SYS_sendmsg,
    libc::SYS_recvmsg,
    libc::SYS_shutdown,
    libc::SYS_bind,
    libc::SYS_listen,
    libc::SYS_getsockname,
    libc::SYS_getpeername,
    libc::SYS_socketpair,
    libc::SYS_setsockopt,
    libc::SYS_getsockopt,
    libc::SYS_clone,
    libc::SYS_fork,
    libc::SYS_vfork,
    libc::SYS_execve,
    libc::SYS_exit,
    libc::SYS_wait4,
    libc::SYS_kill,
    libc::SYS_uname,
    libc::SYS_semget,
    libc::SYS_semop,
    libc::SYS_semctl,
    libc::SYS_shmdt,
    libc::SYS_msgget,
    libc::SYS_msgsnd,
    libc::SYS_msgrcv,
    libc::SYS_msgctl,
    libc::SYS_fcntl,
    libc::SYS_flock,
    libc::SYS_fsync,
    libc::SYS_fdatasync,
    libc::SYS_truncate,
    libc::SYS_ftruncate,
    libc::SYS_getdents,
    libc::SYS_getcwd,
    libc::SYS_chdir,
    libc::SYS_fchdir,
    libc::SYS_rename,
    libc::SYS_mkdir,
    libc::SYS_rmdir,
    libc::SYS_creat,
    libc::SYS_link,
    libc::SYS_unlink,
    libc::SYS_symlink,
    libc::SYS_readlink,
    libc::SYS_chmod,
    libc::SYS_fchmod,
    libc::SYS_chown,
    libc::SYS_fchown,
    libc::SYS_lchown,
    libc::SYS_umask,
    libc::SYS_gettimeofday,
    libc::SYS_getrlimit,
    libc::SYS_getrusage,
    libc::SYS_sysinfo,
    libc::SYS_times,
    libc::SYS_getuid,
    libc::SYS_syslog,
    libc::SYS_getgid,
    libc::SYS_setuid,
    libc::SYS_setgid,
    libc::SYS_geteuid,
    libc::SYS_getegid,
    libc::SYS_setpgid,
    libc::SYS_getppid,
    libc::SYS_getpgrp,
    libc::SYS_setsid,
    libc::SYS_setreuid,
    libc::SYS_setregid,
    libc::SYS_getgroups,
    libc::SYS_setgroups,
    libc::SYS_setresuid,
    libc::SYS_getresuid,
    libc::SYS_setresgid,
    libc::SYS_getresgid,
    libc::SYS_getpgid,
    libc::SYS_setfsuid,
    libc::SYS_setfsgid,
    libc::SYS_getsid,
    libc::SYS_capget,
    libc::SYS_capset,
    libc::SYS_rt_sigpending,
    libc::SYS_rt_sigtimedwait,
    libc::SYS_rt_sigqueueinfo,
    libc::SYS_rt_sigsuspend,
    libc::SYS_sigaltstack,
    libc::SYS_utime,
    libc::SYS_mknod,
    libc::SYS_personality,
    libc::SYS_ustat,
    libc::SYS_statfs,
    libc::SYS_fstatfs,
    libc::SYS_getpriority,
    libc::SYS_setpriority,
    libc::SYS_sched_setparam,
    libc::SYS_sched_getparam,
    libc::SYS_sched_setscheduler,
    libc::SYS_sched_getscheduler,
    libc::SYS_sched_get_priority_max,
    libc::SYS_sched_get_priority_min,
    libc::SYS_sched_rr_get_interval,
    libc::SYS_mlock,
    libc::SYS_munlock,
    libc::SYS_mlockall,
    libc::SYS_munlockall,
    libc::SYS_vhangup,
    libc::SYS_prctl,
    libc::SYS_arch_prctl,
    libc::SYS_setrlimit,
    libc::SYS_sync,
    libc::SYS_gettid,
    libc::SYS_futex,
    libc::SYS_sched_setaffinity,
    libc::SYS_sched_getaffinity,
    libc::SYS_set_tid_address,
    libc::SYS_fadvise64,
    libc::SYS_timer_create,
    libc::SYS_timer_settime,
    libc::SYS_timer_gettime,
    libc::SYS_timer_getoverrun,
    libc::SYS_timer_delete,
    libc::SYS_clock_settime,
    libc::SYS_clock_gettime,
    libc::SYS_clock_getres,
    libc::SYS_clock_nanosleep,
    libc::SYS_exit_group,
    libc::SYS_epoll_wait,
    libc::SYS_epoll_ctl,
    libc::SYS_tgkill,
    libc::SYS_utimes,
    libc::SYS_mbind,
    libc::SYS_set_mempolicy,
    libc::SYS_get_mempolicy,
    libc::SYS_waitid,
    libc::SYS_inotify_init,
    libc::SYS_inotify_add_watch,
    libc::SYS_inotify_rm_watch,
    libc::SYS_openat,
    libc::SYS_mkdirat,
    libc::SYS_mknodat,
    libc::SYS_fchownat,
    libc::SYS_futimesat,
    libc::SYS_newfstatat,
    libc::SYS_unlinkat,
    libc::SYS_renameat,
    libc::SYS_linkat,
    libc::SYS_symlinkat,
    libc::SYS_readlinkat,
    libc::SYS_fchmodat,
    libc::SYS_faccessat,
    libc::SYS_pselect6,
    libc::SYS_ppoll,
    libc::SYS_set_robust_list,
    libc::SYS_get_robust_list,
    libc::SYS_splice,
    libc::SYS_tee,
    libc::SYS_sync_file_range,
    libc::SYS_vmsplice,
    libc::SYS_utimensat,
    libc::SYS_epoll_pwait,
    libc::SYS_signalfd,
    libc::SYS_timerfd_create,
    libc::SYS_eventfd,
    libc::SYS_fallocate,
    libc::SYS_timerfd_settime,
    libc::SYS_timerfd_gettime,
    libc::SYS_accept4,
    libc::SYS_signalfd4,
    libc::SYS_eventfd2,
    libc::SYS_epoll_create1,
    libc::SYS_dup3,
    libc::SYS_pipe2,
    libc::SYS_inotify_init1,
    libc::SYS_preadv,
    libc::SYS_pwritev,
    libc::SYS_recvmmsg,
    libc::SYS_prlimit64,
    libc::SYS_sendmmsg,
    libc::SYS_getcpu,
    libc::SYS_getrandom,
    libc::SYS_memfd_create,
    libc::SYS_execveat,
    libc::SYS_mlock2,
    libc::SYS_copy_file_range,
    libc::SYS_preadv2,
    libc::SYS_pwritev2,
    libc::SYS_statx,
    libc::SYS_rseq,
    libc::SYS_clone3,
    libc::SYS_close_range,
    libc::SYS_openat2,
    libc::SYS_pidfd_open,
    libc::SYS_faccessat2,
    libc::SYS_getdents64,
];
